name: eslint-prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci
        working-directory: ./typescript

      - name: Run ESLint (Code Quality Check)
        run: npm run lint
        working-directory: ./typescript

      - name: Run Prettier (Formatting Check)
        run: npx prettier --check "**/*.ts"
        working-directory: ./typescript
